services:
  broker:
    image: redis:7-alpine
    container_name: churn_redis
    ports:
      - "6379:6379"
    networks:
      - churn_net

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: churn_api
    ports:
      - "8000:8000"
    environment:
      REDIS_URL: redis://broker:6379/0
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_MODEL_NAME: language_detector
      MLFLOW_MODEL_STAGE: Production
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: datasets
      MINIO_MODELS_BUCKET: models
    depends_on:
      - broker
      - mlflow
      - minio
    networks:
      - churn_net

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: churn_worker
    environment:
      REDIS_URL: redis://broker:6379/0
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_MODEL_NAME: language_detector
      MLFLOW_MODEL_STAGE: Production
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: datasets
      MINIO_MODELS_BUCKET: models
    depends_on:
      - broker
      - mlflow
      - minio
    networks:
      - churn_net

  minio:
    image: minio/minio:latest
    container_name: churn_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./data/minio:/data
    networks:
      - churn_net

  minio-mc:
    image: minio/mc:latest
    container_name: churn_minio_mc
    depends_on:
      - minio
    volumes:
      - ./:/work
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set myminio http://minio:9000 minioadmin minioadmin;
      mc mb myminio/datasets --ignore-existing;
      mc mb myminio/models --ignore-existing;
      mc mb myminio/mlflow --ignore-existing;
      echo 'Бакеты datasets, models и mlflow готовы';
      tail -f /dev/null;
      "
    networks:
      - churn_net

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: churn_mlflow
    ports:
      - "5000:5000"
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_DEFAULT_REGION: us-east-1
    depends_on:
      - minio
      - minio-mc
    command: >
      mlflow server
      --host 0.0.0.0
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --default-artifact-root s3://mlflow/artifacts/
    volumes:
      - ./data/mlflow:/mlflow
    networks:
      - churn_net

networks:
  churn_net:
    driver: bridge
